name: TalesOfBrave
options:
  bundleIdPrefix: com.Vincent-Gunawan
  settings:
    iOS:
      TARGETED_DEVICE_FAMILY: "1"  # 1 for iPhone, 2 for iPad
packages:
  Lottie:
    url: https://github.com/airbnb/lottie-spm.git
    minorVersion: 4.2.0
targets:
  TalesOfBrave:
    type: application
    platform: iOS
    deploymentTarget: "16.4"
    sources:
      - TalesOfBrave
    settings:
          base:
            CODE_SIGN_ENTITLEMENTS: TalesOfBrave/TalesOfBrave.entitlements
    dependencies:
      - package: Lottie

